_target_: src.models.nette_module.NetteLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 4e-4
  weight_decay: 0.0

scheduler:
  _target_: pl_bolts.optimizers.lr_scheduler.LinearWarmupCosineAnnealingLR
  _partial_: true
  warmup_epochs: 20
  max_epochs: 50
  warmup_start_lr: 4e-7
  eta_min: 4e-6

net:
  _target_: src.models.components.metaformer.backbone.MetaFormer





# compile model for faster training with pytorch 2.0
compile: false
